name: Split Modules

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  split_modules:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - path: 'admin'
            repository: 'ti-module-admin'
          - path: 'main'
            repository: 'ti-module-main'
          - path: 'system'
            repository: 'ti-module-system'

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Module Split of app/${{ matrix.package.path }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: ${GITHUB_REF#refs/heads/}

          package_directory: 'app/${{ matrix.package.path }}'
          repository_organization: 'tastyigniter'
          repository_name: '${{ matrix.package.repository }}'
          user_name: "Sam Poyigi"
          user_email: "6567634+sampoyigi@users.noreply.github.com"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Modules Tagged Split of ${{ matrix.package.path }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: 'app/${{ matrix.package.path }}'
          repository_organization: 'tastyigniter'
          repository_name: '${{ matrix.package.repository }}'
          user_name: "Sam Poyigi"
          user_email: "6567634+sampoyigi@users.noreply.github.com"
