name: Compile Assets

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies
        working-directory: ./app/admin/assets
        run: npm ci

      - name: Compile assets
        working-directory: ./app/admin/assets
        run: npm run prod

      - name: Commit compiled files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compile Assets
          commit_options: '--no-verify --signoff'
          file_pattern: app/
